apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxdata
data:
  index.html: |
    <h1 style="font-size:30px">Hello World!!</h1></br></br>
    <p style="font-size:30px">{{ .Chart.Name }} : {{ .Chart.Version }}</P>
