apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.fullname" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.port   }}
      protocol: TCP
      targetPort: 80
  selector:
    {{- include "demo-app.selectorLabels" . | nindent 4 }}
