apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.port   }}
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
